steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/first-rank-coders/auth-service',
        '-f',
        'apps/auth-service/Dockerfile',
        '.'
      ]

# Push image to Container Registry / Artifact Registry
images:
  - 'gcr.io/first-rank-coders/auth-service'

# Fix for your logging error
options:
  logging: CLOUD_LOGGING_ONLY
