steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/first-rank-coders/auth-service',
        '-f',
        'apps/auth-service/Dockerfile',
        '.'
      ]

  # Deploy with env file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'auth-service',
        '--image',
        'gcr.io/first-rank-coders/auth-service',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--env-vars-file',
        'apps/auth-service/env.yaml'
      ]

images:
  - 'gcr.io/first-rank-coders/auth-service'

options:
  logging: CLOUD_LOGGING_ONLY
