version: '3.8'
services:
  auth-service:
    build: .
    working_dir: /app/apps/auth-service
    command: npm run start:auth-service
    ports:
      - '3001:8080'
    env_file:
    - ./apps/auth-service/.env
    

  order-service:
    build: .
    working_dir: /app/apps/order-service
    command: npm run start:dev:order-service
    ports:
      - '3002:8080'
    env_file:
    - ./apps/order-service/.env

    

  product-service:
    build: .
    working_dir: /app/apps/product-service
    command: npm run start:product-service
    ports:
      - '3003:8080'
    env_file:
    - ./apps/product-service/.env
